name: Svuota vecchie Run
on:
  workflow_dispatch: # Questo ti permette di avviarlo manualmente con un tasto

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancella le run
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0 # Cancella tutto
          keep_minimum_runs: 0 # Non tiene nessuna run di salvataggio
